{{- if and (eq .Values.analytics.cronjob.enabled true) (eq .Values.analytics.enabled true) }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    app: nkp-cluster-cleaner
  name: nkp-cluster-cleaner-analytics
  namespace: kommander
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: {{ $.Values.analytics.cronjob.failedJobsHistoryLimit }}
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: nkp-cluster-cleaner
            image: {{ $.Values.deployment.image }}
            command:
            - nkp-cluster-cleaner
            args:
            - collect-analytics
            env:
            - name: "REDIS_HOST"
              value: "{{ $.Values.analytics.redis.hostname }}"
            - name: "REDIS_PORT"
              value: "{{ $.Values.analytics.redis.port }}"
            - name: "REDIS_DB"
              value: "{{ $.Values.analytics.redis.db }}"
            - name: "KUBECONFIG" 
              value: "/config/kube/kubeconfig"
            - name: "CONFIG" 
              value: "/config/app/config.yaml"
            volumeMounts:
            - name: kubeconfig
              mountPath: /config/kube
              readOnly: true
            - name: config
              mountPath: /config/app
              readOnly: true
          volumes:
          - name: kubeconfig
            secret:
              secretName: {{ $.Values.app.kubeconfigSecretRef }}
              defaultMode: 0444
          - name: config
            configMap:
              name: nkp-cluster-cleaner-config 
              defaultMode: 0444
  schedule: "{{ $.Values.analytics.cronjob.schedule }}"
  successfulJobsHistoryLimit: {{ $.Values.analytics.cronjob.successfulJobsHistoryLimit }}
{{- end }}
