{{- if eq .Values.analytics.enabled true }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    app: nkp-cluster-cleaner
  name: nkp-cluster-cleaner-analytics
  namespace: kommander
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: {{ $.Values.analytics.failedJobsHistoryLimit }}
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: nkp-cluster-cleaner
            image: {{ $.Values.deployment.image }}
            command:
            - nkp-cluster-cleaner
            args:
            - collect-analytics
            env:
            - name: "REDIS_HOST"
              value: "{{ $.Values.redis.hostname }}"
            - name: "REDIS_PORT"
              value: "{{ $.Values.redis.port }}"
            - name: "REDIS_DB"
              value: "{{ $.Values.redis.db }}"
{{- if eq .Values.valkey.enabled true }}
            - name: "REDIS_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: "{{ $.Values.valkey.secretName }}"
                  key: "{{ $.Values.valkey.secretPasswordKey }}"
{{- else if eq .Values.redis.authentication.enabled true }}
            - name: "REDIS_USERNAME"
              valueFrom:
                secretKeyRef:
                  name: "{{ $.Values.redis.authentication.secretName }}"
                  key: "{{ $.Values.redis.authentication.secretUsernameKey }}"
            - name: "REDIS_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: "{{ $.Values.redis.authentication.secretName }}"
                  key: "{{ $.Values.redis.authentication.secretPasswordKey }}"
{{- end }}
            - name: "KUBECONFIG" 
              value: "/config/kube/kubeconfig"
            - name: "CONFIG" 
              value: "/config/app/config.yaml"
            volumeMounts:
            - name: kubeconfig
              mountPath: /config/kube
              readOnly: true
            - name: config
              mountPath: /config/app
              readOnly: true
          volumes:
          - name: kubeconfig
            secret:
              secretName: {{ $.Values.app.kubeconfigSecretRef }}
              defaultMode: 0444
          - name: config
            configMap:
              name: nkp-cluster-cleaner-config 
              defaultMode: 0444
  schedule: "{{ $.Values.analytics.schedule }}"
  successfulJobsHistoryLimit: {{ $.Values.analytics.successfulJobsHistoryLimit }}
{{- end }}
