apiVersion: apps/v1
kind: Deployment
metadata:
  name: nkp-cluster-cleaner
  namespace: kommander
  labels:
    app: nkp-cluster-cleaner
spec:
  replicas: {{ $.Values.deployment.replicas }}
  selector:
    matchLabels:
      app: nkp-cluster-cleaner
  template:
    metadata:
      labels:
        app: nkp-cluster-cleaner
    spec:
      containers:
      - name: nkp-cluster-cleaner
        image: {{ $.Values.deployment.image }}
        command:
        - nkp-cluster-cleaner
        args:
        - serve 
        - --host 
        - 0.0.0.0 
        - --kubeconfig 
        - /config/kube/kubeconfig
        - --config 
        - /config/app/config.yaml
        - --prefix
        - {{ $.Values.ingress.prefix }}
        - --redis-host
        - {{ $.Values.analytics.redis.hostname }}
        - --redis-port
        - "{{ $.Values.analytics.redis.port }}"
        - --redis-db
        - "{{ $.Values.analytics.redis.db }}"
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: kubeconfig
          mountPath: /config/kube
          readOnly: true
        - name: config
          mountPath: /config/app
          readOnly: true
      volumes:
      - name: kubeconfig
        secret:
          secretName: {{ $.Values.app.kubeconfigSecretRef }}
          defaultMode: 0444
      - name: config
        configMap:
          name: nkp-cluster-cleaner-config 
          defaultMode: 0444

