apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/auth-response-headers: X-Forwarded-User
    kubernetes.io/ingress.class: kommander-traefik
    traefik.ingress.kubernetes.io/router.tls: "true"
  name: nkp-cluster-cleaner
  namespace: kommander
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: nkp-cluster-cleaner
            port:
              number: 80
        path: {{ $.Values.ingress.prefix }}
        pathType: ImplementationSpecific
