apiVersion: v1
kind: Service
metadata:
  name: nkp-cluster-cleaner
  namespace: kommander
spec:
  selector:
    app: nkp-cluster-cleaner
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: http