name: Catalog Packaging

on:
  workflow_run:
    workflows: ["Publish Helm Chart"]
    types:
      - completed

jobs:
  validate-catalog:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate catalog repository
        run: |
          docker run --rm \
            --entrypoint /opt/nkp/nkp \
            -v ${{ github.workspace }}:/workspace \
            -w /workspace \
            mesosphere/nkp-distributor-linux:v2.16.0 \
            validate catalog-repository

  # Note the use of /mdr as the volume path, this is because the
  # nkp create catalog commands use the current working directory as
  # a project name.
  create-catalog-bundle:
    runs-on: ubuntu-latest
    needs: validate-catalog
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create catalog bundle
        run: |
          docker run --rm \
            --entrypoint /opt/nkp/nkp \
            -v ${{ github.workspace }}:/mdr \
            -w /mdr \
            mesosphere/nkp-distributor-linux:v2.16.0 \
            create catalog-bundle --output-file nkp-cluster-cleaner.tar

      - name: Upload catalog bundle artifact
        uses: actions/upload-artifact@v4
        with:
          name: catalog-bundle
          path: nkp-cluster-cleaner.tar
          retention-days: 1

  push-catalog-bundle:
    runs-on: ubuntu-latest
    needs: create-catalog-bundle
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download catalog bundle artifact
        uses: actions/download-artifact@v4
        with:
          name: catalog-bundle

      - name: Push catalog bundle
        run: |
          docker run --rm \
            --entrypoint /opt/nkp/nkp \
            -v ${{ github.workspace }}:/mdr \
            -w /mdr \
            mesosphere/nkp-distributor-linux:v2.16.0 \
            push bundle --bundle nkp-cluster-cleaner.tar \
              --to-registry ghcr.io/markround/catalog \
              --to-registry-username ${{ github.actor }} \
              --to-registry-password ${{ secrets.GITHUB_TOKEN }}